name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Clean
        run: xcodebuild -scheme McBopomofo -configuration Release clean
      - name: Clean
        run: xcodebuild -scheme McBopomofoInstaller -configuration Release clean
      - name: Build
        run: xcodebuild -scheme McBopomofo -configuration Release build
      - name: Build
        run: xcodebuild -scheme McBopomofoInstaller -configuration Release build
      - name: Test CandidateUI
        run: swift test
        working-directory: Packages/CandidateUI
      - name: Test CandidateUI
        run: swift test
        working-directory: Packages/CandidateUI
      - name: Test OpenCCBridge
        run: swift test
        working-directory: Packages/OpenCCBridge
      - name: Test VXHanConvert
        run: swift test
        working-directory: Packages/VXHanConvert
