name: Build-with-macOS-latest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build (latest)
    runs-on: macOS-latest
    env:
        GIT_SSL_NO_VERIFY: true
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v1
      - name: Clean
        run: make clean
      - name: Build
        run: git pull --all && git submodule sync; make update; make
